### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by avan411** [mjakeman/devs-hackathon-2021#4]
compile presentation information

- [x] select a name
- [x] problem statement
- [x] the opportunity
- [x] the offering 

- design for longevity
- design for scalability
- design for reusability
- design for simplicity

- [x] value proposition
- [x] high level prototyping

- [x] customer profile

- [x] market segment discussion

- [x] competition overview
- [x] stakeholder analysis
- [x] management team
- [x] high level prototyping

**Comment by mjakeman** [comment]
Done! :)
